services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
      restart: always
      environment:
        discovery.type: single-node
        xpack.security.enabled: false
      ports:
        - 9200:9200
      volumes:
        - elasticdata:/usr/share/elasticsearch/data

    kibana:
      image: docker.elastic.co/kibana/kibana:8.15.2
      restart: always
      environment:
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ports:
        - 5601:5601  # Kibana default port
    
volumes:
  elasticdata: