# Generated by Django 5.1 on 2024-10-06 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["due_date", "status"]},
        ),
    ]
