# Generated by Django 5.1 on 2024-10-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0009_task_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("None", "None"),
                ],
                max_length=10,
            ),
        ),
    ]
